version: '3.7'

services:
  redis-master:
    image: redis
    container_name: redis-master
    hostname: redis-master
    volumes:
      - "./.data:/data"
    ports:
      - "6380:6379"
    networks:
      - network1

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    links:
      - redis-master
    ports:
      - "8085:8081"
    networks:
      - network1

  redis-slave-1:
    image: redis
    container_name: redis-slave-1
    hostname: redis-slave-1
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    volumes:
      - "./.data:/data"
    ports:
      - "6381:6379"
    networks:
      - network1

  redis-slave-2:
    image: redis
    container_name: redis-slave-2
    hostname: redis-slave-2
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    volumes:
      - "./.data:/data"
    ports:
      - "6382:6379"
    networks:
      - network1

  # Instance 1
  redis-sentinel-1:
    build:
      context: ./redis-sentinel
    container_name: redis-sentinel-1
    hostname: redis-sentinel-1
    links:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    ports:
      - "6391:6379"
      - "26381:26379"
    networks:
      - network1

  # Instance 2
  redis-sentinel-2:
    build:
      context: ./redis-sentinel
    container_name: redis-sentinel-2
    hostname: redis-sentinel-2
    links:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    ports:
      - "6392:6379"
      - "26382:26379"
    networks:
      - network1

  redis-sentinel-3:
    build:
      context: ./redis-sentinel
    container_name: redis-sentinel-3
    hostname: redis-sentinel-3
    links:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    ports:
      - "6393:6379"
      - "26383:26379"
    networks:
      - network1

networks:
  network1:
    name: redis-net
    external: true
